language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
script: cargo test --all
branches:
  only:
  - master

matrix:
  allow_failures:
  - rust: stable # TODO(eddyb) remove when 1.32 is released
